"""MVRV x Sentiment: do valuation + fear flag good moments to buy? (horizon-aware)

Tests two of the most popular retail beliefs - "buy when MVRV is low" and "be greedy
when others are fearful" - as CONDITIONAL forward returns by (MVRV state x sentiment
state), across horizons from 90 days to 540 days (~1.5 years).

The key lesson of this file is HORIZON DEPENDENCE:
  - At short horizons (<=365d) momentum dominates: buying "expensive + greed" beats
    buying "cheap + fear". The contrarian signal underperforms.
  - At cycle-scale horizons (540d) it FLIPS for BTC: "cheap + fear" outperforms and
    "expensive + greed" underperforms - the valuation/mean-reversion story finally
    shows up at the timescale these indicators are actually used on.

Heavy caveat, quantified in the output: at 540d the conditioning windows overlap
almost completely, so a "state" spans ~1 independent episode (the 2022 bottom).
This is a CASE STUDY of one cycle bottom, not a statistically powered test. Testing
a cycle-timing rule properly needs multiple bottoms (=> more history, ~2011+).

Look-ahead-safe: MVRV uses an expanding percentile (past+present only); Fear&Greed
uses absolute thresholds (no fitting). Run: python utils/mvrv_sentiment.py
Writes: data/mvrv_sentiment.csv, docs/results/MVRV_SENTIMENT_RESULTS.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.feature_engineering import load_engineered_frames  # noqa: E402
from utils.cycle_timing import expanding_percentile, forward_return  # noqa: E402

HORIZONS = (90, 180, 365, 540)
MV_LO, MV_HI = 0.33, 0.67          # MVRV percentile terciles
FG_FEAR, FG_GREED = 45, 55         # Fear & Greed absolute thresholds


def _prep(df):
    return pd.DataFrame({
        "mvp": expanding_percentile(df["CapMVRVCur"]),
        "mv": df["CapMVRVCur"],
        "fg": df["FearGreedValue"],
    })


def analyse(asset, df):
    base = _prep(df)
    rows = []
    for h in HORIZONS:
        f = forward_return(df["PriceUSD"], h)
        d = base.join(f.rename("f")).dropna()
        mvrv = np.where(d.mvp < MV_LO, "cheap", np.where(d.mvp > MV_HI, "expensive", "mid"))
        sent = np.where(d.fg < FG_FEAR, "fear", np.where(d.fg > FG_GREED, "greed", "neutral"))
        d = d.assign(mvrv=mvrv, sent=sent)
        baseline = d.f.mean()
        states = {
            "baseline": d,
            "cheap+fear": d[(d.mvrv == "cheap") & (d.sent == "fear")],
            "deepcheap+extremefear": d[(d.mvp < 0.20) & (d.fg < 25)],
            "expensive+greed": d[(d.mvrv == "expensive") & (d.sent == "greed")],
        }
        for name, sub in states.items():
            rows.append({
                "asset": asset, "horizon_days": h, "state": name,
                "mean_fwd": float(sub.f.mean()) if len(sub) else np.nan,
                "vs_baseline": float(sub.f.mean() - baseline) if len(sub) else np.nan,
                "n_days": len(sub),
                "n_indep": max(1, len(sub) // h),          # ~ independent (non-overlapping) episodes
            })
        # full 3x3 quadrant at this horizon
        for mv_b in ["cheap", "mid", "expensive"]:
            for s_b in ["fear", "neutral", "greed"]:
                sub = d[(d.mvrv == mv_b) & (d.sent == s_b)]
                rows.append({"asset": asset, "horizon_days": h, "state": f"grid:{mv_b}+{s_b}",
                             "mean_fwd": float(sub.f.mean()) if len(sub) else np.nan,
                             "vs_baseline": float(sub.f.mean() - baseline) if len(sub) else np.nan,
                             "n_days": len(sub), "n_indep": max(1, len(sub) // h)})
    return pd.DataFrame(rows)


def main():
    btc, ada = load_engineered_frames()
    res = pd.concat([analyse("BTC", btc), analyse("ADA", ada)], ignore_index=True)
    res.to_csv(_ROOT / "data" / "mvrv_sentiment.csv", index=False)
    print("Saved data/mvrv_sentiment.csv")
    _write_markdown(res)


def _pct(v):
    return "n/a" if pd.isna(v) else f"{v:+.0%}"


def _write_markdown(res: pd.DataFrame):
    md = _ROOT / "docs" / "results" / "MVRV_SENTIMENT_RESULTS.md"
    md.parent.mkdir(parents=True, exist_ok=True)
    key = res[~res.state.str.startswith("grid:")]

    L = [
        "# MVRV_SENTIMENT_RESULTS.md - do valuation + fear flag good moments to buy?",
        "",
        "Conditional forward returns by **MVRV state x sentiment state**, across horizons.",
        "Tests the folklore: *'buy low MVRV'* and *'be greedy when others are fearful'*.",
        "MVRV = look-ahead-safe expanding percentile (cheap <0.33, expensive >0.67);",
        "sentiment = Fear&Greed (fear <45, greed >55). Generated by "
        "`python utils/mvrv_sentiment.py`.",
        "",
        "## Bottom line - it depends entirely on the HORIZON",
        "",
        "- **Short horizon (<=365d): momentum wins, the folklore LOSES.** 'Cheap + fear' "
        "underperforms; 'expensive + greed' outperforms. Buying into strength beat buying "
        "into fear.",
        "- **Cycle horizon (540d ~1.5y): it FLIPS for BTC.** 'Cheap + fear' outperforms the "
        "baseline and 'expensive + greed' underperforms - the valuation/mean-reversion story, "
        "at the timescale these indicators are actually used on. **This retro-corrects the "
        "short-horizon 'cycle-timing refuted' finding** in `CYCLE_TIMING_RESULTS.md` / "
        "`REGIME_EVENT_RESULTS.md`: those were <=180d and thus horizon-blind.",
        "- **BUT n is tiny at long horizons** (see `n_indep`): at 540d a 'state' spans ~1 "
        "independent episode (the 2022 bottom). This is a **case study of one cycle bottom, "
        "not a powered test.** And **ADA does not flip** even at 540d - the effect isn't "
        "universal. Properly testing a cycle rule needs multiple bottoms (=> history back to "
        "~2011; note Fear&Greed only exists from 2018).",
        "",
        "## The horizon story - key states vs baseline",
        "",
    ]
    for asset in ["BTC", "ADA"]:
        L += [f"### {asset}",
              "",
              "| Horizon | Baseline | Cheap+Fear | Deepcheap+ExtremeFear | Expensive+Greed | ~indep (C+F) |",
              "|---------|----------|------------|-----------------------|-----------------|--------------|"]
        for h in HORIZONS:
            sub = key[(key.asset == asset) & (key.horizon_days == h)].set_index("state")
            def g(s): return _pct(sub.loc[s, "mean_fwd"]) if s in sub.index else "n/a"
            ni = int(sub.loc["cheap+fear", "n_indep"]) if "cheap+fear" in sub.index else 0
            L.append(f"| {h}d | {g('baseline')} | {g('cheap+fear')} | "
                     f"{g('deepcheap+extremefear')} | {g('expensive+greed')} | ~{ni} |")
        L.append("")
    L += ["> Read each cell vs that row's Baseline. At 540d, BTC Cheap+Fear jumps *above* "
          "baseline while Expensive+Greed drops *below* it - the reversal. `~indep` shows why "
          "the long-horizon numbers are illustrative (near-1 independent episode).",
          "",
          "## Full quadrant (MVRV x sentiment), 90d vs 540d",
          ""]
    for asset in ["BTC", "ADA"]:
        for h in (90, 540):
            g = res[(res.asset == asset) & (res.horizon_days == h) & res.state.str.startswith("grid:")]
            piv = {}
            for _, r in g.iterrows():
                _, cell = r.state.split(":")
                mv_b, s_b = cell.split("+")
                piv.setdefault(mv_b, {})[s_b] = (r.mean_fwd, r.n_days)
            L += [f"**{asset}, forward {h}d** (mean return, n days):", "",
                  "| MVRV \\ Sentiment | Fear | Neutral | Greed |",
                  "|------------------|------|---------|-------|"]
            for mv_b in ["cheap", "mid", "expensive"]:
                cells = []
                for s_b in ["fear", "neutral", "greed"]:
                    mv, n = piv.get(mv_b, {}).get(s_b, (np.nan, 0))
                    cells.append(f"{_pct(mv)} (n={n})")
                L.append(f"| **{mv_b}** | " + " | ".join(cells) + " |")
            L.append("")
    L += ["## Honest conclusion",
          "",
          "Valuation + sentiment did **not** give a usable short-term buy signal (momentum "
          "dominated). At cycle horizons BTC shows the textbook reversal - buying cheap+fear "
          "and holding ~1.5 years beat the market - but this rests on **one** bear bottom "
          "(2022), does not replicate on ADA, and cannot be powered without more cycles of "
          "history. Best read as: *the valuation/sentiment 'buy the fear' rule is a long-cycle "
          "idea our ~1.5-cycle sample can illustrate for BTC but not statistically confirm.*",
          ""]
    md.write_text("\n".join(L), encoding="utf-8")
    print(f"Saved {md}")


if __name__ == "__main__":
    main()
